#!/bin/sh

echo DEBUG=0 >> .env
echo DATABASE_DRIVER=com.mysql.cj.jdbc.Driver >> .env
echo DATABASE_HOST=$DATABASE_HOST >> .env
echo DATABASE_NAME=$DATABASE_NAME >> .env
echo DATABASE_PASSWORD=$DATABASE_PASSWORD >> .env
echo DATABASE_PORT=$DATABASE_PORT >> .env
echo DATABASE_USERNAME=$DATABASE_USERNAME >> .env
echo LOG_LEVEL=$LOG_LEVEL >> .env
echo LOG_PATH=$LOG_PATH >> .env
echo SHARED_SECRET_KEY=$SHARED_SECRET_KEY >> .env
echo REDIS_URI=$REDIS_URI >> .env
echo SHOW_SQL=$SHOW_SQL >> .env
echo IMAGE=$DOCKER_REGISTRY/$APP_NAME >> .env
echo API_SERVICE_IMAGE=$DOCKER_REGISTRY/$APP_NAME:api-service >> .env
echo CI_REGISTRY=$DOCKER_REGISTRY >> .env
echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION >> .env
echo REDIS_HOST=$REDIS_HOST >> .env
echo REDIS_PASSWORD=$REDIS_PASSWORD >> .env
echo EMAIL_DEBUG_MODE=$EMAIL_DEBUG_MODE >> .env
echo EMAIL_FROM=$EMAIL_FROM >> .env
echo EMAIL_SMTP_HOST=$EMAIL_SMTP_HOST >> .env
echo EMAIL_SMTP_USERNAME=$EMAIL_SMTP_USERNAME >> .env
echo EMAIL_STMP_PASSWORD=$EMAIL_STMP_PASSWORD >> .env