spring:
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
            required: 'true'
          auth: 'true'
          port: '25'
        transport:
          protocol: smtp
        debug: ${EMAIL_DEBUG_MODE:}
    host: ${EMAIL_SMTP_HOST:}
    username: ${EMAIL_SMTP_USERNAME:}
    password: ${EMAIL_STMP_PASSWORD:}
email:
  from: ${EMAIL_FROM:}
