version: '3.8'

services:
  api-service:
    image: "${API_SERVICE_IMAGE}"
    container_name: odpj-api-admin
    env_file: .env
    restart: always
    ports:
      - "8083:8083"

    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "api-admin"